In [14]:
data_dir = r"E:\project\chitra"
from pathlib import Path
out_dir = Path(data_dir) / "output"

out_dir.mkdir(exist_ok=True, parents=True)

In [24]:
from pathlib import Path

data_path = Path(data_dir) / "Chitra_global_Report.tsv.txt"

import pandas as pd
data = pd.read_csv(data_path, sep="\t")

In [25]:
data

,PG.ProteinAccessions,PG.Genes,PG.Organisms,PG.ProteinDescriptions,PG.ProteinNames,AC02_CP_R1,AC02_CP_R2,AA05_CP_R1,AA05_CP_R2,RWT_CP_R1,...,AA05_Golgi_R1,AA05_Golgi_R2,RWT_Golgi_R1,RWT_Golgi_R2,R02_Golgi_R1,R02_Golgi_R2,R05_Golgi_R1,R05_Golgi_R2,CC_Golgi_R1,CC_Golgi_R2
0,A0A024R1R8;Q9Y2S6,TMA7B;TMA7,Homo sapiens,Translation machinery-associated protein 7B;Tr...,TMA7B_HUMAN;TMA7_HUMAN,361.543945,1569.807129,220.222992,1517.179321,1100.726685,...,122.885643,276.574280,375.728668,247.744720,228.023651,258.670898,NaN,NaN,329.625793,463.715240
1,A0A024RBG1,NUDT4B,Homo sapiens,Diphosphoinositol polyphosphate phosphohydrola...,NUD4B_HUMAN,NaN,NaN,NaN,63.281170,NaN,...,NaN,NaN,215.980667,178.280197,203.430542,118.208328,NaN,NaN,NaN,NaN
2,A0A087WUV0,ZNF892,Homo sapiens,Zinc finger protein 892,ZN892_HUMAN,95.944618,62.960506,151.888626,68.203918,71.885612,...,88.402115,97.721680,91.145729,77.300026,65.116417,95.442291,86.886139,69.674759,79.724838,NaN
3,A0A096LP01,SMIM26,Homo sapiens,Small integral membrane protein 26,SIM26_HUMAN,930.513733,300.031860,1023.884521,237.555786,263.249084,...,251.497772,210.297134,295.318512,193.561600,179.502594,214.170746,292.835632,162.126282,304.908966,162.934403
4,A0A096LP49,CCDC187,Homo sapiens,Coiled-coil domain-containing protein 187,CC187_HUMAN,134.972809,NaN,NaN,NaN,NaN,...,NaN,71.142342,NaN,56.286049,61.902065,85.880760,NaN,30.320551,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10762,Q9Y6X5,ENPP4,Homo sapiens,Bis(5'-adenosyl)-triphosphatase ENPP4,ENPP4_HUMAN,1725.375000,1007.741333,1897.689209,1167.992188,975.614929,...,959.635132,1671.656006,1907.428223,1425.448975,1287.893433,1321.362427,798.350952,746.007446,1685.824097,1799.164673
10763,Q9Y6X8,ZHX2,Homo sapiens,Zinc fingers and homeoboxes protein 2,ZHX2_HUMAN,247.585663,292.436890,205.726456,274.921478,284.360168,...,131.521988,155.868118,NaN,114.537590,88.354889,148.314758,124.676483,126.542305,NaN,NaN
10764,Q9Y6X9,MORC2,Homo sapiens,ATPase MORC2,MORC2_HUMAN,3411.315186,2216.833008,4146.708496,2315.182861,2027.160156,...,1705.010010,834.808106,775.881348,908.924988,751.773193,834.722046,1469.451050,1523.155029,714.470398,484.896942
10765,Q9Y6Y0,IVNS1ABP,Homo sapiens,Influenza virus NS1A-binding protein,NS1BP_HUMAN,310.150909,382.761871,304.171997,288.943542,271.619446,...,850.331055,313.039429,488.305267,428.078857,461.651977,486.965973,632.247925,893.007202,660.916748,548.027466
10766,Q9Y6Y8,SEC23IP,Homo sapiens,SEC23-interacting protein,S23IP_HUMAN,1505.972412,2127.178711,1253.917603,2270.009277,2239.076172,...,4801.929688,9950.600586,8443.341797,8857.035156,7250.470215,8799.422852,5899.868164,5443.028320,16707.046880,18061.996090

In [26]:
data['Protein'] = [i.split(";")[0] for i in data['PG.ProteinAccessions']]
data.set_index('Protein', inplace=True)
data

,PG.ProteinAccessions,PG.Genes,PG.Organisms,PG.ProteinDescriptions,PG.ProteinNames,AC02_CP_R1,AC02_CP_R2,AA05_CP_R1,AA05_CP_R2,RWT_CP_R1,...,AA05_Golgi_R1,AA05_Golgi_R2,RWT_Golgi_R1,RWT_Golgi_R2,R02_Golgi_R1,R02_Golgi_R2,R05_Golgi_R1,R05_Golgi_R2,CC_Golgi_R1,CC_Golgi_R2
Protein,,,,,,,,,,,,,,,,,,,,,
A0A024R1R8,A0A024R1R8;Q9Y2S6,TMA7B;TMA7,Homo sapiens,Translation machinery-associated protein 7B;Tr...,TMA7B_HUMAN;TMA7_HUMAN,361.543945,1569.807129,220.222992,1517.179321,1100.726685,...,122.885643,276.574280,375.728668,247.744720,228.023651,258.670898,NaN,NaN,329.625793,463.715240
A0A024RBG1,A0A024RBG1,NUDT4B,Homo sapiens,Diphosphoinositol polyphosphate phosphohydrola...,NUD4B_HUMAN,NaN,NaN,NaN,63.281170,NaN,...,NaN,NaN,215.980667,178.280197,203.430542,118.208328,NaN,NaN,NaN,NaN
A0A087WUV0,A0A087WUV0,ZNF892,Homo sapiens,Zinc finger protein 892,ZN892_HUMAN,95.944618,62.960506,151.888626,68.203918,71.885612,...,88.402115,97.721680,91.145729,77.300026,65.116417,95.442291,86.886139,69.674759,79.724838,NaN
A0A096LP01,A0A096LP01,SMIM26,Homo sapiens,Small integral membrane protein 26,SIM26_HUMAN,930.513733,300.031860,1023.884521,237.555786,263.249084,...,251.497772,210.297134,295.318512,193.561600,179.502594,214.170746,292.835632,162.126282,304.908966,162.934403
A0A096LP49,A0A096LP49,CCDC187,Homo sapiens,Coiled-coil domain-containing protein 187,CC187_HUMAN,134.972809,NaN,NaN,NaN,NaN,...,NaN,71.142342,NaN,56.286049,61.902065,85.880760,NaN,30.320551,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q9Y6X5,Q9Y6X5,ENPP4,Homo sapiens,Bis(5'-adenosyl)-triphosphatase ENPP4,ENPP4_HUMAN,1725.375000,1007.741333,1897.689209,1167.992188,975.614929,...,959.635132,1671.656006,1907.428223,1425.448975,1287.893433,1321.362427,798.350952,746.007446,1685.824097,1799.164673
Q9Y6X8,Q9Y6X8,ZHX2,Homo sapiens,Zinc fingers and homeoboxes protein 2,ZHX2_HUMAN,247.585663,292.436890,205.726456,274.921478,284.360168,...,131.521988,155.868118,NaN,114.537590,88.354889,148.314758,124.676483,126.542305,NaN,NaN
Q9Y6X9,Q9Y6X9,MORC2,Homo sapiens,ATPase MORC2,MORC2_HUMAN,3411.315186,2216.833008,4146.708496,2315.182861,2027.160156,...,1705.010010,834.808106,775.881348,908.924988,751.773193,834.722046,1469.451050,1523.155029,714.470398,484.896942
Q9Y6Y0,Q9Y6Y0,IVNS1ABP,Homo sapiens,Influenza virus NS1A-binding protein,NS1BP_HUMAN,310.150909,382.761871,304.171997,288.943542,271.619446,...,850.331055,313.039429,488.305267,428.078857,461.651977,486.965973,632.247925,893.007202,660.916748,548.027466
Q9Y6Y8,Q9Y6Y8,SEC23IP,Homo sapiens,SEC23-interacting protein,S23IP_HUMAN,1505.972412,2127.178711,1253.917603,2270.009277,2239.076172,...,4801.929688,9950.600586,8443.341797,8857.035156,7250.470215,8799.422852,5899.868164,5443.028320,16707.046880,18061.996090

In [28]:
rows = []

for index,row in data.iterrows():
    proteins = row['PG.ProteinAccessions'].split(";")
    if pd.isna(row['PG.Genes']):
        continue
    genes  = row['PG.Genes'].split(";")

    # print(proteins, genes)
    for protein, gene in zip(proteins, genes):
        rows.append([protein, gene])


with open(out_dir / "protein_gene_map.tsv", "w") as f:
    f.write("Protein\tGene\n")
    for protein, gene in rows:
        f.write(f"{protein}\t{gene}\n")

In [29]:
data.drop(columns=['PG.ProteinAccessions','PG.Genes','PG.Organisms','PG.ProteinDescriptions','PG.ProteinNames'], inplace=True)

In [30]:
data

,AC02_CP_R1,AC02_CP_R2,AA05_CP_R1,AA05_CP_R2,RWT_CP_R1,RWT_CP_R2,R02_CP_R1,R02_CP_R2,R05_CP_R1,R05_CP_R2,...,AA05_Golgi_R1,AA05_Golgi_R2,RWT_Golgi_R1,RWT_Golgi_R2,R02_Golgi_R1,R02_Golgi_R2,R05_Golgi_R1,R05_Golgi_R2,CC_Golgi_R1,CC_Golgi_R2
Protein,,,,,,,,,,,,,,,,,,,,,
A0A024R1R8,361.543945,1569.807129,220.222992,1517.179321,1100.726685,1469.521729,1276.981689,296.837524,140.551315,1381.658569,...,122.885643,276.574280,375.728668,247.744720,228.023651,258.670898,NaN,NaN,329.625793,463.715240
A0A024RBG1,NaN,NaN,NaN,63.281170,NaN,NaN,NaN,NaN,NaN,105.273628,...,NaN,NaN,215.980667,178.280197,203.430542,118.208328,NaN,NaN,NaN,NaN
A0A087WUV0,95.944618,62.960506,151.888626,68.203918,71.885612,69.475441,92.483307,131.505997,106.437981,80.262688,...,88.402115,97.721680,91.145729,77.300026,65.116417,95.442291,86.886139,69.674759,79.724838,NaN
A0A096LP01,930.513733,300.031860,1023.884521,237.555786,263.249084,222.243988,298.655395,1014.427307,903.794861,230.410416,...,251.497772,210.297134,295.318512,193.561600,179.502594,214.170746,292.835632,162.126282,304.908966,162.934403
A0A096LP49,134.972809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,71.142342,NaN,56.286049,61.902065,85.880760,NaN,30.320551,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q9Y6X5,1725.375000,1007.741333,1897.689209,1167.992188,975.614929,915.989807,977.915649,2098.498291,2717.568604,1098.487305,...,959.635132,1671.656006,1907.428223,1425.448975,1287.893433,1321.362427,798.350952,746.007446,1685.824097,1799.164673
Q9Y6X8,247.585663,292.436890,205.726456,274.921478,284.360168,268.731750,261.930176,278.545532,280.231476,241.777557,...,131.521988,155.868118,NaN,114.537590,88.354889,148.314758,124.676483,126.542305,NaN,NaN
Q9Y6X9,3411.315186,2216.833008,4146.708496,2315.182861,2027.160156,2155.240723,2079.165771,3459.358887,3830.535400,2270.193359,...,1705.010010,834.808106,775.881348,908.924988,751.773193,834.722046,1469.451050,1523.155029,714.470398,484.896942
Q9Y6Y0,310.150909,382.761871,304.171997,288.943542,271.619446,330.730804,382.945068,343.533234,273.925171,292.057831,...,850.331055,313.039429,488.305267,428.078857,461.651977,486.965973,632.247925,893.007202,660.916748,548.027466
Q9Y6Y8,1505.972412,2127.178711,1253.917603,2270.009277,2239.076172,2153.423096,2165.978271,1501.103882,1643.626709,2414.875244,...,4801.929688,9950.600586,8443.341797,8857.035156,7250.470215,8799.422852,5899.868164,5443.028320,16707.046880,18061.996090

In [32]:
import numpy as np
data.map(np.log2)

,AC02_CP_R1,AC02_CP_R2,AA05_CP_R1,AA05_CP_R2,RWT_CP_R1,RWT_CP_R2,R02_CP_R1,R02_CP_R2,R05_CP_R1,R05_CP_R2,...,AA05_Golgi_R1,AA05_Golgi_R2,RWT_Golgi_R1,RWT_Golgi_R2,R02_Golgi_R1,R02_Golgi_R2,R05_Golgi_R1,R05_Golgi_R2,CC_Golgi_R1,CC_Golgi_R2
Protein,,,,,,,,,,,,,,,,,,,,,
A0A024R1R8,8.498027,10.616372,7.782821,10.567176,10.104241,10.521131,10.318522,8.213530,7.134953,10.432185,...,6.941173,8.111523,8.553547,7.952711,7.833040,8.014974,NaN,NaN,8.364685,8.857095
A0A024RBG1,NaN,NaN,NaN,5.983704,NaN,NaN,NaN,NaN,NaN,6.718000,...,NaN,NaN,7.754758,7.478003,7.668392,6.885188,NaN,NaN,NaN,NaN
A0A087WUV0,6.584130,5.976375,7.246870,6.091783,6.167631,6.118431,6.531121,7.038985,6.733869,6.326658,...,6.466009,6.610607,6.510103,6.272397,6.024949,6.576557,6.441054,6.122564,6.316957,NaN
A0A096LP01,9.861884,8.228972,9.999837,7.892123,8.040285,7.796001,8.222338,9.986450,9.819852,7.848062,...,7.974402,7.716285,8.206128,7.596649,7.487861,7.742618,8.193947,7.340974,8.252235,7.348147
A0A096LP49,7.076525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.152637,NaN,5.814705,5.951916,6.424263,NaN,4.922224,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q9Y6X5,10.752694,9.976910,10.890028,10.189815,9.930168,9.839188,9.933566,11.035142,11.408101,10.101302,...,9.906342,10.707062,10.897413,10.477201,10.330798,10.367811,9.640879,9.543046,10.719238,10.813112
Q9Y6X8,7.951784,8.191982,7.684584,8.102876,8.151576,8.070023,8.033038,8.121769,8.130475,7.917537,...,7.039160,7.284182,NaN,6.839677,6.465238,7.212518,6.962046,6.983476,NaN,NaN
Q9Y6X9,11.736112,11.114284,12.017751,11.176910,10.985244,11.073633,11.021789,11.756289,11.903330,11.148599,...,10.735564,9.705301,9.599692,9.828017,9.554154,9.705152,10.521062,10.572847,9.480730,8.921534
Q9Y6Y0,8.276827,8.580303,8.248744,8.174644,8.085443,8.369514,8.580994,8.424306,8.097638,8.190110,...,9.731881,8.290201,8.931640,8.741733,8.850662,8.927677,9.304347,9.802528,9.368325,9.098104
Q9Y6Y8,10.556480,11.054726,10.292227,11.148482,11.128688,11.072416,11.080803,10.551808,10.682667,11.237733,...,12.229399,13.280568,13.043598,13.112608,12.823859,13.103193,12.526467,12.410194,14.028169,14.140670

In [35]:
data.map(np.log2).to_csv(out_dir / "protein_log2_abundance_matrix.tsv", sep="\t")